### ISSUE TITLE
StackBlitz Link

### ISSUE THREAD

**Issue by ghost** [rstropek-teaching/turmrechnen-quiz-4bhif-micky8186#1]
The App can be tested via StackBlitz: https://angular-turmrechnen.stackblitz.io
The source code is available in this repo.

**Comment by rstropek** [comment]
Hi @micky8186 

Thank you for the link. It works as expected, your extra point is secured.

However, I recommend that you refactor your solution. Building the HTML in TypeScript and using a binding to `innerHTML` is not optimal. Prefer an `*ngFor` loop instead.

Greetings,
Rainer Stropek.
